name: Print Revelio Version
description: retrieves the version from the Revelio demo site
modules:
  - http = http
steps:
  - baseUrl = http://demo.getrevelio.com 
  - start = startTimer
  - response = http.get:
      url: $baseUrl/api/version
  - http.isOk: $response
  - version = http.body: $response
  - stopTimer: $start
  - log: Current Revelio version is ${version}. That took $start.milliseconds milliseconds