name: printRevelioVersion
description: retrieves the version from the Revelio demo site
steps:
- baseUrl = http://demo.getrevelio.com 
- start = startTimer
- version = get:
    url: $baseUrl/api/version
- areEqual:
    expected: 200
    actual: $version.statusCode
- stopTimer: $start
- log:
  - Current Revelio version is %s. That took %s milliseconds
  - $version.body
  - $start.milliseconds