name: useCustomFunctions
functions:
  getCurrentDate: return new Date()
  timeInUtc:
    - dt
    - return dt.toGMTString()
steps:
- currentDate = getCurrentDate
- log: The current date is $currentDate 
- currentDateInUtc = timeInUtc:
    dt: $currentDate
- log: The current date in UTC is $currentDateInUtc